### ISSUE TITLE
panic marshalling list in map[string]any

### ISSUE THREAD

**Issue by dezren39** [sblinch/kdl-go#3] opened 2023-12-23 11:17 UTC
hello,

i'm looking at using kdl with viper, and am having an issue with a test case.

```
var data = map[string]any{
	"key": "value",
	// "list": []any{
	// 	"item1",
	// 	"item2",
	// 	"item3",
	// },
	"map": map[string]any{
		"key": "value",
	},
	"nested_map": map[string]any{
		"map": map[string]any{
			"key": "value",
			"list": []any{
				"item1",
				"item2",
				"item3",
			},
		},
	},
}
```
this test case can be turned into a kdl byte string without issue, but if i uncomment the list above then i get a panic.
if i uncomment the list above and then wrap the entire object in another map[string]any then that also works.
```
var data = map[string]any{
	"results": map[string]any{
		"key": "value",
		"list": []any{
			"item1",
			"item2",
			"item3",
		},
		"map": map[string]any{
			"key": "value",
		},
		"nested_map": map[string]any{
			"map": map[string]any{
				"key": "value",
				"list": []any{
					"item1",
					"item2",
					"item3",
				},
			},
		},
	},
}
```

here is the panic i get
```
Running tool: C:\Program Files\Go\bin\go.exe test -timeout 30s -run ^TestCodec_Encode$ github.com/spf13/viper/internal/encoding/kdl

--- FAIL: TestCodec_Encode (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x20e960]

goroutine 6 [running]:
testing.tRunner.func1.2({0x2f5220, 0x5a4e60})
	C:/Program Files/Go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
	C:/Program Files/Go/src/testing/testing.go:1548 +0x397
panic({0x2f5220?, 0x5a4e60?})
	C:/Program Files/Go/src/runtime/panic.go:914 +0x21f
github.com/sblinch/kdl-go/internal/marshaler.marshalSliceToNode(0x2f3d20?, {0x33bd68, 0x4}, {0x2dcfc0?, 0xc000008120?, 0x0?}, 0x0)
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:158 +0x680
github.com/sblinch/kdl-go/internal/marshaler.marshalValueToNode(0xc0000ffe60, {0x33bd68, 0x4}, {0x2dcfc0?, 0xc000008120?, 0x18b434b0108?}, 0x0)
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:544 +0xce9
github.com/sblinch/kdl-go/internal/marshaler.marshalValueToNode(0xc0000ffe60, {0x33bd68, 0x4}, {0x2ed140?, 0xc000032620?, 0x98?}, 0x0)
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:548 +0xc8d
github.com/sblinch/kdl-go/internal/marshaler.marshalMapToNodes(0x30?, {0x2f23a0?, 0xc00002d170?, 0x18b434b0108?}, {0x0?, 0x0, 0x0})
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:70 +0x23b
github.com/sblinch/kdl-go/internal/marshaler.marshalValueToNodes(0x100?, {0x2f23a0?, 0xc00002d170?, 0x1000013804d?})
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:725 +0x150
github.com/sblinch/kdl-go/internal/marshaler.MarshalWithOptions({0x2f23a0, 0xc00002d170}, 0xc0000ffea8, {})
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:47 +0x107
github.com/sblinch/kdl-go/internal/marshaler.Marshal(...)
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/internal/marshaler/marshal.go:37
github.com/sblinch/kdl-go.Marshal({0x2f23a0, 0xc00002d170})
	C:/Users/drewr/go/pkg/mod/github.com/sblinch/kdl-go@v0.0.0-20231112203113-9fa9a505b79a/marshal.go:52 +0x76
github.com/spf13/viper/internal/encoding/kdl.Codec.Encode(...)
	c:/Users/drewr/viper/internal/encoding/kdl/codec.go:9
github.com/spf13/viper/internal/encoding/kdl.TestCodec_Encode(0x0?)
	c:/Users/drewr/viper/internal/encoding/kdl/codec_test.go:86 +0x2a
testing.tRunner(0xc00006f6c0, 0x36d4f8)
	C:/Program Files/Go/src/testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	C:/Program Files/Go/src/testing/testing.go:1648 +0x3ad
FAIL	github.com/spf13/viper/internal/encoding/kdl	0.443s
FAIL
```

**Comment by dezren39** [comment] 2023-12-24 15:15
so with this
```
key "value"
map "skipped"
map key="skipped" key="value"
nested_map {
map key="value" 17 {
	list "item1" "item2" "item3"
	mixup ""=1 2 3 4
	first "first"=1 2 3 4
	child ""=1 2 3 4 { "" 5 ; "" 6 ; }
}
}
```

i get unmarshal errors from map being there twice, i think because the type changes. but i think it should just replace the type and the last one should win? any other option gets complicated, but i dont think it should throw because its valid kdl?

separate issue `{ "" 5 ; "" 6 ; }` is valid kdl but seems to cause an issue. i think semicolon isn't correctly being handled. `{
"" 5
"" 6 }` works fine

**Comment by dezren39** [comment] 2023-12-27 14:21
I've come to understand that my initial issue may have been caused by my triggering the key=val logic as described in the docs, https://github.com/sblinch/kdl-go/blob/main/docs/marshal.md

> If the slice is of type []interface{}, elements of type []interface{}{"key", value} are treated as properties, and all other elements are treated as arguments.

this is pretty cool actually and i like this but it did surprise me. is there a toggle somewhere? i'm learning as I go and see that kdl-go has already thought of most of the things that have come to mind for me. :-) closing this 'working as intended' unless you think otherwise can reopen? it may be nice to get an error message instead of a panic, panics make me sad.

**Comment by dezren39** [comment] 2023-12-27 14:43
actually, reopening this because I tried using a string using

> If the slice is of type []string, elements containing an equal sign (=) are treated as properties by splitting them at the equal sign (eg: in name=John, name becomes the key and John becomes the value), and all other elements are treated as arguments.


```
			input: map[string]interface{}{
				"null":    nil,
				"boolean": true,
				"color":   "gold",
				"number":  int64(123),
				"string":  "Hello World",
				// "array":   []interface{}{1, 2, 3, 4, 5}, // https://github.com/sblinch/kdl-go/issues/3
				"stringarray": []string{"1", "2", "3", "4", "5"},
				"object":      map[string]interface{}{"a": "b", "c": "d"},
			},
```

and still got panic same as before. none of these have an '=' so each of the stringarray values should be put into arguments right? .1 = "1" and so on?

**Comment by sblinch** [comment] 2024-01-08 03:39
> this test case can be turned into a kdl byte string without issue, but if i uncomment the list above then i get a panic.

Fixed, thank you!

> actually, reopening this because I tried using a string using

Can't reproduce with the info you've provided. If the problem was not resolved by the fix for the above issue, please open a new issue with a complete test case and I'll investigate.

**Closed as completed by sblinch** 2024-01-08 03:39 UTC

**Comment by dezren39** [comment] 2024-01-08 17:17
Thanks I'll try again soon!
